<?xml version="1.0"?>
<robot name='robot' xmlns:xacro="http://ros.org/eiki/xacro">
    
    <xacro:include filename="$(find robot_description)/urdf/gazebo.urdf.xacro" />
    <xacro:include filename="$(find robot_description)/urdf/robot_lidar.urdf.xacro" />
    <xacro:include filename="$(find robot_description)/urdf/depth.urdf.xacro" />
    <!-- Robot properites -->
    <xacro:property name="base_width" value="0.31"/>
    <xacro:property name="base_length" value="0.42"/>
    <xacro:property name="base_height" value="0.18"/>

    <xacro:property name="wheel_radius" value="0.10"/>
    <xacro:property name="wheel_width" value="0.04"/>
    <xacro:property name="wheel_ygap" value="0.025"/>
    <xacro:property name="wheel_zoff" value="0.05"/>
    <xacro:property name="wheel_xoff" value="0.12"/>

    <xacro:property name="caster_xoff" value="0.14"/>


    <!-- Inertial properties -->
    <xacro:macro name="box_inertia" params="m w h d">
        <inertial>
              <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
              <mass value="${m}"/>
              <inertia ixx="${(m/12) * (h*h + d*d)}" ixy="0.0" ixz="0.0" iyy="${(m/12) * (w*w + d*d)}" iyz="0.0" izz="${(m/12) * (w*w + h*h)}"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertia" params="m r h">
        <inertial>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            <mass value="${m}"/>
            <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy = "0" ixz = "0" iyy="${(m/12) * (3*r*r + h*h)}" iyz = "0" izz="${(m/2) * (r*r)}"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="sphere_inertia" params="m r">
        <inertial>
            <mass value="${m}"/>
            <inertia ixx="${(2/5) * m * (r*r)}" ixy="0.0" ixz="0.0" iyy="${(2/5) * m * (r*r)}" iyz="0.0" izz="${(2/5) * m * (r*r)}"/>
        </inertial>
    </xacro:macro>

    <!-- Robot Base -->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="blue">
                <color rgba="0 0 1.0 1.0"/>
            </material>
        </visual>

        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
        </collision>

        <xacro:box_inertia m="12" w="${base_width}" d="${base_length}" h="${base_height}"/>
    </link>

    <xacro:macro name="snowman_sphere" params="prefix parent r m h">
        <link name="${prefix}_link">
            <visual>
                <geometry>
                    <sphere radius="${r}"/>
                </geometry>
                <material name="White">
                    <color rgba="1.0 1.0 1.0 1.0"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${r}"/>
                </geometry>
            </collision>
            <xacro:sphere_inertia m="${m}" r="${r}"/>
        </link>

        <joint name="${prefix}_joint" type="fixed">
            <parent link="${parent}"/>
            <child link="${prefix}_link"/>
            <origin xyz="0 0 ${h}" rpy="0 0 0"/>
        </joint>
    </xacro:macro>

    <xacro:snowman_sphere prefix="lower_sphere" parent="base_link" r="0.09" m="2" h="${base_height}"/>
    <xacro:snowman_sphere prefix="middle_sphere" parent="lower_sphere_link" r="0.07" m="1.5" h="${0.09+0.06}"/>
    <xacro:snowman_sphere prefix="top_sphere" parent="middle_sphere_link" r="0.05" m="0.7" h="${0.07+0.04}"/>

    <link name="nose_link">
        <visual>
            <geometry>
                <cylinder radius="0.01" length="0.05"/>
            </geometry>
            <material name="Orange">
                <color rgba="1.0 0.1 0.0 1.0"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.01" length="0.2"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="0.4" r="0.01" h="0.05"/>
    </link>

    <joint name="nose_joint" type="fixed">
        <parent link="top_sphere_link"/>
        <child link="nose_link"/>
        <origin xyz="0.045 0 0" rpy="0 ${pi/2} 0"/>
    </joint>

    <xacro:macro name="snowman_eye" params="prefix parent s">
        <link name="${prefix}_link">
            <visual>
                <geometry>
                    <sphere radius="0.007"/>
                </geometry>
                <material name="Black">
                    <color rgba="0.0 0.0 0.0 1.0"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="0.007"/>
                </geometry>
            </collision>
            <xacro:sphere_inertia m="0.01" r="0.007"/>
        </link>

        <joint name="${prefix}_joint" type="fixed">
            <parent link="${parent}"/>
            <child link="${prefix}_link"/>
            <origin xyz="0.04 ${s} 0.025" rpy="0 0 0"/>
        </joint>
    </xacro:macro>

    <xacro:snowman_eye prefix="left_eye" parent="top_sphere_link" s="0.02"/>
    <xacro:snowman_eye prefix="right_eye" parent="top_sphere_link" s="-0.02"/>


    <link name="base_footprint"/>

    <joint name="base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0.0 0.0 ${-(wheel_radius+wheel_zoff)}" rpy="0 0 0"/>
    </joint>

    <!-- Wheel macro -->
    <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
        <link name="${prefix}_link">
            <visual>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <material name="Gray">
                    <color rgba="0.5 0.5 0.5 1.0"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
            </collision>

            <xacro:cylinder_inertia m="1" r="${wheel_radius}" h="${wheel_width}"/>
        </link>

        <joint name="${prefix}_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_link"/>
            <origin xyz="${x_reflect*wheel_xoff} ${y_reflect*(base_width/2+wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
        </joint>
    </xacro:macro>

    <xacro:wheel prefix="drivewhl_l" x_reflect="-1" y_reflect="1"/>
    <xacro:wheel prefix="drivewhl_r" x_reflect="-1" y_reflect="-1"/>


    <!-- Front smaller wheel -->
    <link name="front_caster">
        <visual>
            <geometry>
                <sphere radius="${(wheel_radius+wheel_zoff-(base_height/2))}"/>
            </geometry>
            <material name="Cyan">
                <color rgba="0 1.0 1.0 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${(wheel_radius+wheel_zoff-(base_height/2))}"/>
            </geometry>
        </collision>

        <xacro:sphere_inertia m="5" r="${(wheel_radius+wheel_zoff-(base_height/2))}"/>
    </link>

    <joint name="caster_joint" type="continuous">
        <parent link="base_link"/>
        <child link="front_caster"/>
        <origin xyz="${caster_xoff} 0.0 ${-(base_height/2)}" rpy="0 0 0"/>
        <axis xyz="1 0 0"/>
    </joint>

    <gazebo reference="front_caster">
        <material>Gazebo/White</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

</robot>
